#pragma once

#include <algorithm>
#include <array>
#include <bitset>
#include <chrono>
#include <execution>
#include <functional>
#include <iostream>
#include <iterator>
#include <list>
#include <numeric>
#include <optional>
#include <ranges>
#include <sstream>
#include <string_view>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <vector>
